### PR TITLE
Cli progress update fix

### LINKED ISSUE #141: [BUG] CLI prints a lot of unneeded output when pulling a docker image
**Describe the bug**
When pulling a tool image, the Kiln CLI fills a users terminal scrollback with a lot of duplicate status lines about the download progress.

**To Reproduce**
1. Ensure you have no kiln/bundler-audit docker images locally by running `docker rmi --force $(docker images -q kiln/bundler-audit | uniq)`
2. Ensure the CLI tool is built by navigating to project root and running `cargo make build-kiln-cli`
3. Start an integration testing stack
4. Add a `kiln.toml` file to a Ruby project you have locally (I tested with RailsGoat but any should work) with the app name and url for your integration testing stack data collector (host.docker.internal for MacOS)
5. Run `../path/to/kiln/bin/cli ruby dependencies` and the CLI tool should pull the docker image needed, filling terminal scrollback with useless information

**Expected behavior**
Download progress to be reported in a concise way

**Screenshots**

**Environment details**
- Component: Kiln CLI
- Commit: 6c2acb4f43878caf99c4376e1e97a83f9816fca8

**Additional context**

### PR DESCRIPTION
**Pull request by DM-sb**
# What does this PR change?
Uses the indicatif crate to fix the issue of progress messages when pulling tool images inside the kiln cli 

# Why is it important?
Fixes #141

# Checklist
- [ ] Tests added/updated as appropriate
- [ ] Documentation added/updated as appropriate

If this PR introduces a new tool:
- [ ] Documentation on how to handle false positives added
- [ ] Documentation on how to configure the tool added

### CODE REVIEW

File: cli/src/main.rs [hunk 1]
```diff
@@ -217,17 +231,170 @@ fn validate_config_info(config_info: &CliConfigOptions) -> Result<(), ConfigFile
...
+        if output["id"] != serde_json::Value::Null {
+            if output["status"] != serde_json::Value::Null {
+                if self.pull_started == true { 
+                    let status = output["status"].as_str().unwrap().to_string(); 
+                    let id = output["id"].as_str().unwrap().to_string();
+                    match self.prog_channels.get(&id) {
+                        Some(trx) => 
+                            trx.lock().unwrap().send(output).unwrap(), 
+                        None => { 
+                            println!("Cannot find channel for sending progress update message in kiln-cli for id {} and status {}",id, status);
```
Comment (DanHatesNumbers) [inline cli/src/main.rs]: Because this is an error state, could you change this to `eprintln!` please so that the output is sent to stderr?

**Comment by DanHatesNumbers** [comment]
LGTM, once CI passes, let's merge this!
